### ISSUE TITLE
restdoc.web.controller.obj.VOKt#getROOT_NAV全局变量BUG

### ISSUE THREAD

**Issue by marsxuefeng** [Open-source-sharing/REST-doc#17]
restdoc.web.controller.obj.VOKt#getROOT_NAV属于全局变量 不可以在其他地方修改

**Comment by Maple-mxf** [comment]
`@Deprecated(message = "Global Var immutable")
val ROOT_NAV: NavNode = NavNode(
        id = "root",
        title = "一级目录",
        field = "title",
        children = mutableListOf(),
        href = null,
        pid = "0",
        checked = true)`

**Comment by marsxuefeng** [comment]
```
@Deprecated(message = "Global Var immutable")
val ROOT_NAV: NavNode = NavNode(
        id = "root",
        title = "一级目录",
        field = "title",
        children = mutableListOf(),
        href = null,
        pid = "0",
        checked = true)
```
